'use client';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

const TireStacks = () => {
    const { nodes, materials } = useGLTF('/models/tireStacks.glb');

    return (
        <RigidBody
            // type="dynamic"
            type="fixed"
            // mass={0.5}
            colliders="cuboid"
            // friction={0.1}
            // restitution={1}
            name="tires"
            // onWake={}
        >
            <group dispose={null}>
                <mesh
                    geometry={nodes.tire056.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire063.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire070.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire077.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire057.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire064.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire071.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire078.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire058.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire065.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire072.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire079.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire059.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire066.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire073.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire080.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire060.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire067.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire074.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire081.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire061.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire068.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire075.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire082.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire062.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire069.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire076.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire083.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire027.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire020.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire041.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire034.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire055.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire048.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire013.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire006.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire014.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire021.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire028.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire035.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire042.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire049.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire007.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire015.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire022.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire029.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire036.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire043.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire050.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire001.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire008.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire016.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire023.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire030.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire037.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire044.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire051.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire002.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire009.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire017.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire024.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire031.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire038.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire045.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire052.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire003.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire010.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire018.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire032.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire039.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire046.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire053.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire004.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire019.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire026.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire033.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire040.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire047.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire054.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire005.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire012.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire025.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire011.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire084.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire085.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire098.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire099.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire112.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire113.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire126.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire127.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire086.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire087.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire100.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire101.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire114.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire115.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire128.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire129.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire088.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire089.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire102.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire103.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire116.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire117.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire130.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire131.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire090.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire091.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire104.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire105.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire118.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire119.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire132.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire133.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire092.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire093.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire106.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire107.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire120.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire121.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire134.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire135.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire094.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire095.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire108.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire109.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire122.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire123.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire136.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire137.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire096.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire097.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire110.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire111.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire124.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire125.geometry}
                    material={materials.White}
                />
                <mesh
                    geometry={nodes.tire138.geometry}
                    material={materials.Blue}
                />
                <mesh
                    geometry={nodes.tire139.geometry}
                    material={materials.Blue}
                />
            </group>
        </RigidBody>
    );
};
useGLTF.preload('/models/tireStacks.glb');

export default TireStacks;
