'use client';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

const Skills = () => {
    const { nodes, materials } = useGLTF('/models/skills.glb');

    const blueGlow = new THREE.MeshStandardMaterial({
        color: new THREE.Color(0x007bff),
        emissive: new THREE.Color(0x007bff),
        emissiveIntensity: 1.2,
    });

    return (
        <group dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.flask.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tailwind.geometry}
                material={materials.tailwind}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.prisma.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.react.geometry}
                material={materials.react}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.redux.geometry}
                material={materials.redux}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.vercel.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.docker.geometry}
                material={materials.docker}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.github.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.skillsGrid.geometry}
                material={blueGlow}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve030.geometry}
                material={materials.awsOrange}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve030_1.geometry}
                material={materials.awsBlue}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve032.geometry}
                material={materials.White}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve032_1.geometry}
                material={materials.BlenderBlue}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve032_2.geometry}
                material={materials.blenderOrange}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve021.geometry}
                material={materials.css}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve021_1.geometry}
                material={materials.csslight}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve021_2.geometry}
                material={materials.White}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve016.geometry}
                material={materials.git}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve016_1.geometry}
                material={materials.White}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve036.geometry}
                material={materials.htmllight}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve036_1.geometry}
                material={materials.White}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve036_2.geometry}
                material={materials.htmlorange}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve037.geometry}
                material={materials['SVGMat.010']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve037_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve042.geometry}
                material={materials['Curve.025_Baked']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve042_1.geometry}
                material={materials['Curve.026_Baked']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve042_2.geometry}
                material={materials['SVGMat.009']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve042_3.geometry}
                material={materials['Curve.024_Baked']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve045.geometry}
                material={materials.python}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve045_1.geometry}
                material={materials.pythonyellow}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve060.geometry}
                material={materials.White}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve060_1.geometry}
                material={materials.TypeScript}
            />
        </group>
    );
};
useGLTF.preload('/models/skills.glb');

export default Skills;
